from typing import List, Optional
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.services.finding_service import FindingService
from app.schemas.recommendation import RecommendationOut

router = APIRouter(prefix="/recommendations", tags=["Recommendations"])


@router.get("", response_model=List[RecommendationOut], summary="List Least-Privilege Recommendations", description="Retrieves list of recommendations generated by audit.")
def get_recommendations(
    status: Optional[str] = Query(None, description="Filter by status: Pending, Accepted, Rejected, Reviewed"),
    db: Session = Depends(get_db)
):
    return FindingService.get_recommendations(db, status=status)


@router.post("/{id}/accept", response_model=RecommendationOut, summary="Accept Recommendation", description="Marks recommendation as Accepted and resolves finding.")
def accept_recommendation(id: int, db: Session = Depends(get_db)):
    return FindingService.update_recommendation_status(db, rec_id=id, new_status="Accepted")


@router.post("/{id}/reject", response_model=RecommendationOut, summary="Reject Recommendation", description="Marks recommendation as Rejected.")
def reject_recommendation(id: int, db: Session = Depends(get_db)):
    return FindingService.update_recommendation_status(db, rec_id=id, new_status="Rejected")
